#ifndef CORRESPONDENCES_AGGREGATION_H_
#define CORRESPONDENCES_AGGREGATION_H_

/**
 * Applies the Correspondences Aggregator to partitions generated by a DCG.
 *
 * Output:
 *  - k x k Matrix, columns are separated by spaces, rows by a LF
 *      One LF at the end of the output.
 *
 * @param k Number of subclusters.
 * @param hhc Half-half coefficient. Passed to the AffinitiesGenerator.
 * @param l The value of l.
 * @param n Number of individuals n.
 * @param timesteps Number of timesteps.
 * @param d_timesteps Timestep delta. Every d_timesteps generator timestep is added to the
 *      aggregator.
 */
void run(unsigned int k, double hhc, unsigned int l, unsigned int n, double alpha_v,
	unsigned int timesteps, unsigned int d_timesteps
);

#endif /* CORRESPONDENCES_AGGREGATION_H_ */
