#ifndef TRACKING_SUPER_CLUSTER_CUT_H_
#define TRACKING_SUPER_CLUSTER_CUT_H_

/**
 * Evaluates the natural edge cut from different correspondences exploration algorithms.
 * Uses a dynamic network generated by the DynamicCommunitiesGenerator analysing (the same)
 * timesteps with different algorithms.
 *
 * The natural edge cut describes metrics about the correspondences "edges" (between all clusters
 * from the two different sides of each correspondence) which are cut, because the clusters are
 * in different super clusters in the underlying partition of the DynamicCommunitiesGenerator.
 * For evaluation the EdgeCutEvaluation class is used.
 *
 * Output:
 *  - TSV output containing the various metrics aggregated by EdgeCutEvaluation.
 *  - First row (header): "algorithm edges cuts edgeSum cutSum"
 *  - All following rows: The data for different algorithms, separated by a space.
 *  - Included algorithms:
 *     * CheapestMutual
 *     * RecursiveMutual
 *     * TopDownIndividualOptimumWeakenedZero
 *     * LeafExpansion
 *
 * @param k Number of subclusters.
 * @param hhc Half-half coefficient. Passed to the AffinitiesGenerator.
 * @param l The value of l.
 * @param n Number of individuals n.
 * @param timesteps Number of timesteps.
 * @param d_timesteps Timestep delta. Every d_timesteps generator timestep is added to the
 *      aggregator.
 */
void run(unsigned int k, double hhc, unsigned int l, unsigned int n, double alpha_v,
	unsigned int timesteps, unsigned int d_timesteps
);

#endif /* TRACKING_SUPER_CLUSTER_CUT_H_ */
